# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5fa17aab1b895b246161a9ccc8a0c046d43bf07ddc55d61087a076bd15d84e7f44d007d8974d5677ce888fddc67d2c5997a71b64cf69a4e89cfb5407d9eeade2

test:
  secret_key_base: 1c0d1ca2120eb09aef7682f74febd1119cbb5375e1ad39001a3fc717caf72a8576ccbad9b3be13850e2c7263e7f3170a8a1a5735bf39f1aacb60805d354dba51

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
